In [1]:
import os

current_dir = os.getcwd()
print("Current directory:", current_dir)

Current directory: d:\PROJECTS\RecommendIQ\notebooks

In [2]:
os.chdir('..')

In [3]:
from src import recommender

interaction_df = recommender.load_interaction_data(
    "data/features/user_item_features.csv"
)

interaction_df.head()

==================================================
Interaction data loaded successfully.
Number of interactions : 2145179
Number of columns      : 3
==================================================

   visitorid  itemid  interaction_strength
0          0   67045                     1
1          0  285930                     1
2          0  357564                     1
3          1   72028                     1
4          2  216305                     2

In [4]:
interaction_df[
    interaction_df["visitorid"] == 3
]

   visitorid  itemid  interaction_strength
8          3  385090                     1

In [5]:
len(
    interaction_df[
        interaction_df["visitorid"] == 3
    ]
)

1

In [6]:
interaction_df[
    interaction_df["visitorid"] == 3
]["itemid"].unique()

array([385090])

In [7]:
similarity_df = recommender.load_recommender(
    "artifacts/item_similarity.pkl"
)

similarity_df.shape

==================================================
Recommendation model loaded successfully.
Loaded from : artifacts/item_similarity.pkl
==================================================

(5, 5)

In [8]:
385090 in similarity_df.index

False

In [9]:
similarity_df.index.tolist()

[248676, 253185, 318965, 355908, 367447]

In [10]:
from src import recommender

interaction_df = recommender.load_interaction_data(
    "data/features/user_item_features.csv"
)

interaction_df.shape

==================================================
Interaction data loaded successfully.
Number of interactions : 2145179
Number of columns      : 3
==================================================

(2145179, 3)

In [11]:
interaction_matrix = recommender.create_interaction_matrix(
    interaction_df
)

interaction_matrix.shape

==================================================
Creating interaction matrix
Interactions used : 10000
Unique users      : 9698
Unique items      : 8732
==================================================
==================================================
Interaction matrix created successfully.
Users  : 9698
Items  : 8732
==================================================

(9698, 8732)

In [12]:
similarity_df = recommender.train_similarity_model(
    interaction_matrix
)

similarity_df.shape

==================================================
Item similarity model trained successfully.
Number of items : 8732
==================================================

(8732, 8732)

In [13]:
similarity_df = recommender.train_similarity_model(
    interaction_matrix
)

similarity_df.shape

==================================================
Item similarity model trained successfully.
Number of items : 8732
==================================================

(8732, 8732)

In [14]:
recommender.save_recommender(
    similarity_df
)

==================================================
Recommendation model saved successfully.
Saved at : ../artifacts/item_similarity.pkl
==================================================

In [15]:
import os

print(
    os.path.exists(
        "../artifacts/item_similarity.pkl"
    )
)

True

In [16]:
items = interaction_df[
    interaction_df["visitorid"] == 3
]["itemid"].unique()

print("Customer 3 items:", items)

Customer 3 items: [385090]

In [17]:
for item in items:
    print(
        "Item:", item,
        "| In similarity matrix:",
        item in similarity_df.index
    )

Item: 385090 | In similarity matrix: False